config/routes.rb
PhotoBooth::Application.routes.draw do
  root :to => 'User#register'

  mount Resque::Server, :at => "/resque"

  match 'register' => 'User#register', :as => 'register'
  match 'photography' => 'Entry#photography', :as => 'entry_photography'
  match 'editing' => 'Entry#editing', :as => 'entry_editing'
  match 'completed' => 'Entry#completed', :as => 'completed_entries'
  match 'last' => 'Entry#last', :as => 'last_entry'
  get 'generate-nickname(/:fullname)' => 'User#generate_nickname', :as => :nickname
  
  resources :image do
    member do
      get 'open' => 'Entry#open_image'
    end
  end

  #resources :download, :only => [:image]

  resources :entry do
    member do
      get 'photography_start'
      get 'photography_stop'
      get 'photography_completed'
        
      get 'editing_start'
      get 'editing_stop'
      get 'editing_completed'
      
      get 'flag'
      get 'delete'
    end
  end

  match 'image/download/:id'  => 'Entry#download_image',  :as => 'download_image'
  match 'image/upload(/:id)'    => 'Entry#upload_image',    :as => 'upload_image'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
end

app/models/user.rb
class User < ActiveRecord::Base  
  has_many :entries
  has_many :events, :through => :entries
  validates_presence_of :name_first
  validates_presence_of :name_last
  validates_presence_of :hometown
  validates_presence_of :name_nick
  validates :email_address, :presence => {:message => "You must supply and email address."}, :uniqueness => {:case_sensitive => false, :message => "Email address is already being used.", :scope => :type}, :email_format => {:message => 'Must give a valid email address.'}

  attr_accessor :terms
  validates :terms, acceptance: true
end

app/controllers/user_controller.rb
require 'open-uri'
require 'net/http'

class UserController < ApplicationController
  def register
    # AN EXAMPLE OF APPLICATION CONFIGURATION - THIS IS SET IN THE config/environments/development.rb file
    # pp "/* ***********************************************"
    #   pp Rails.configuration.current_event_id
    # pp "*********************************************** */"
    if params[:user]
      @user = User.find_or_create_by_email_address(params[:user][:email_address])
      @user.update_attributes(params[:user])
      if @user && @user.persisted?
        @entry = @user.entries.create(:status => ENTRY_STATUS_REGISTERED, :event => Event.first)
        PrivatePub.publish_to("/queue/photo", {:entry_id => @entry.id, :user => @user, :entry => @entry, :action => 'create'})
        
        # /* ***********************************************
        # NOW THAT THE USER HAS REGISTERED AND AN ENTRY HAS BEEN CREATED - WE SHOULD BE PUSHING A NOTIFICATION TO THE NOTIFICATION CENTER
        # *********************************************** */
        redirect_to(root_path, :notice => 'User has been registered')
      else
        unless @user.errors.empty?
          flash.now[:notice] = "There are errors in the form. Fix the errors and try again."
        end
          
        render :action => 'new'        
      end
    else
      @user = User.new
      render :action => 'new'
    end
  end
  
  def generate_nickname
    nickname = get_nickname(params[:fullname])
    render :text => nickname
  end
  
  def get_nickname(fullname)
    begin
      url = URI.parse('http://www.mess.be/inickgenwuname.php')
      resp,data = Net::HTTP.post_form(url,{realname: fullname})
      results = resp.body.slice(resp.body.index('<font size=2>') + 13, resp.body.length)
      nickname = results.slice(0,results.index('</b>')).gsub!("\n","")
    rescue
      nickname = "no suggestion available"
    end
  end
  helper_method :get_nickname
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<%= stylesheet_link_tag 'registration'%>
<%= image_tag("header_logo.png",class: 'header_logo',id: 'logo') %>
<%= form_for @user, :as => :user, :url => register_path(@user), :method => :put, :html => {:class => 'register_user container form-horizontal', :id => "registration_form"} do |f| %>
  <%= f.hidden_field :tagline, value: MOST_LIKELY_TO[rand(MOST_LIKELY_TO.length)] %>
  <div class="row">
    <div class="span6">
    	<%= f.label :name_first, "First name" %>
    	<% if !@user.errors[:name_first].blank? %>
    	  <% for error in @user.errors[:name_first] %>		
    		<span class="error"><%= error %></span>
    	  <% end %>
    	<% end %>
    	<%= f.text_field :name_first %>
    </div>
    <div class="span6">      
    	<%= f.label :name_last, "Last name" %>
    	<% if !@user.errors[:name_first].blank? %>
    	  <% for error in @user.errors[:name_last] %>		
    		<span class="error"><%= error %></span>
    	  <% end %>
    	<% end %>
    	<%= f.text_field :name_last %>
    </div>
  </div>
  <div class="row">
    <div class="span6">
    	<%= f.label :email_address, "Email Address" %>	
    	<% if !@user.errors[:email_address].blank? %>
    	  <% for error in @user.errors[:email_address] %>		
    		<span class="error"><%= error %></span>
    	  <% end %>
    	<% end %>
    	<%= f.email_field :email_address %>
    </div>
    <div class="span6">
      <%= f.label :name_nick, "Nickname"%>
    	<% if !@user.errors[:name_nick].blank? %>
    	  <% for error in @user.errors[:name_nick] %>		
    		<span class="error"><%= error %></span>
    	  <% end %>
    	<% end %>
      <% if FEATURES[:wutang] %>
        <div class="input-append">
        	<%= f.text_field :name_nick %>
          <% if ping("198.61.209.65") %>
            <button class="btn generate-nickname" href="<%= nickname_path %>" type="button">Generate</button>
          <% end %>        
        </div>
      <% else %>
        <%= f.text_field :name_nick %>      
      <% end %>
      
    </div>
  </div>
	<div class="row">
	  <div class="span6">
    	<%= f.label :hometown, "Hometown" %>	
    	<% if !@user.errors[:hometown].blank? %>
    	  <% for error in @user.errors[:hometown] %>		
    		<span class="error"><%= error %></span>
    	  <% end %>
    	<% end %>      
    	<%= f.text_field :hometown %>	    
	  </div>
	  <div class="span6">
      <%= f.label :attendance, "Attendance" %>
      <%= f.select :attendance, (1..7) %>
	  </div>
	</div>
  <div class="row">
    <div class="span12">
      <label for="user_terms" class="checkbox"><%= f.check_box :terms %> I agree to the terms and conditions</label>  
    	<% if !@user.errors[:terms].blank? %>
    	  <% for error in @user.errors[:terms] %>		
    		<span class="error"><%= error %></span>
    	  <% end %>
    	<% end %>      
    </div>
  </div>
  <div class="row">
    <div id="terms_and_conditions" class="span12 terms">
      <h3>*PLEASE READ THIS DOCUMENT CAREFULLY. By clicking the check box on this legal document, you are giving up legal rights.</h3>

      <h3>RELEASE AND WAIVER</h3>

      <h4>Name of facilitators: Norfork Design Inc. and Red Bull North America, Inc.</h4>

      <p>I desire to participate in one or more activities including, without limitation, a photoshoot with props (the "Activity") provided by the facilitator listed above. In consideration of the opportunity to participate in the Activity and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, I hereby irrevocably and unconditionally agree for myself and my heirs, estate, insurers, successors and assigns as follow:</p>
      <ol>
      	<li><strong>ASSUMPTION OF RISK:</strong> Before participating in the Activity, I will inspect the area and equipment (the "Equipment") to be used by me for the Activity, and if I believe anything is unsafe, I will refuse to participate until the conditions are corrected to my satisfaction. Neither Norfork Design Inc or Red Bull has made any representation to me as to the suitability, condition, or safety of the site of the Activity (the "Facilities") or Equipment used or involved in the Activity. I understand that participation in the Activity involves inherent risks and dangers of accidents, property loss or damage serious personal and bodily injury, death and severe social and economic losses. These may result not only from my own actions, inactions, or negligence, but also from, without limitation, the actions, inactions, or negligence of others, or the condition of the Facilities or Equipment. Further, there may be other risks not known to me or reasonably foreseeable at this time. I understand and I have considered and evaluated the nature, scope and extent of the risks involved, and I voluntarily and freely choose to assume these risks. </li>
      	<li><strong>RELEASE FROM LIABILITY:</strong> I fully and forever release, and discharge Norfork Design Inc and Red Bull and their respective affiliates, directors, officers, shareholders, employees, agents and insurers and all others involved in the Activity (the "Released Parties) from any and all injuries (including death), losses, damages, claims (including negligence claims), demands, lawsuits, expenses and any other liability of any kind, of or to me, my property, or any other person, directly or indirectly arising out of or in connection with my participation in the Activity, including transportation to the Activity, even if it is due to the negligence or other fault of the Released Parties.</li>
      	<li><strong>COVENANT NOT TO SUE:</strong> I will not initiate any claim, lawsuit, court action or other legal proceeding against the Released Parties, nor join or assist in the prosecution of any claim for money or other damages which anyone may have, on account of injuries (including death), losses, damages sustained by me or others in connection with my participation in the Activity, and I waive any right to do so. This means that I cannot sue to hold the Released Parties responsible for any injuries, losses or damages that I may experience resulting from, related to, or in connection with the Activity, even if it is due to the negligence or other fault of the Released Parties. I waive my insurers’ right to make a claim against the Released Parties based on payments by insurers to me or on my behalf for any reason. This means my insurers have no right or subrogation against the Released Parties.</li>
      	<li><strong>INDEMNITY:</strong> I will hold harmless, indemnify and reimburse the Released Parties from and for all damages, sums, costs, or expenses (including legal fees) incurred by any of the Released Parties or paid by them to any person (including me or my insurers) relating to or in connection with any accident, injury (including death), loss or damage sustained by me or others in connection with my participation in the Activity and/or transportation to the Activity. This means that I will reimburse the Released Parties if anyone makes a claim against them based on any accident that I may be involved in or any injuries, losses or damages that I may suffer</li>
      	<li><strong>NO INSURANCE; MEDICAL EXPENSES:</strong> I understand that Norfork Design Inc and Red Bull and others involved in the Activity do NOT provide me with any insurance, either life, medical or liability, for any illness, accident, injury, loss or damage that may arise in connection with my participation in the Activity and/or transportation to the Activity. If I want insurance of any kind, I must obtain it on my own. I will pay my own medical emergency expenses and all subsequent medical expenses in the event of any illness, accident, or injury resulting from, relating to, or in connection with my participation in the Activity and/or transportation to the Activity.</li>
      	<li><strong>AUTHORIZATION:</strong> I authorize and permit Norfork Design Inc to contact emergency services in the event of any illness, accident or injury to me.</li>
      	<li><strong>VALIDITY:</strong> If any portion of this Release and Waiver is held to be invalid or unenforceable, all other provisions nevertheless continue to be valid and enforceable. This Release and Waiver supersedes any oral or written statements made by or to me in connection with the Activity. I understand that I cannot terminate, cancel, or revoke this Release and Waiver for any reason.</li>
      	<li><strong>ALCOHOL &amp; DRUGS:</strong> I attest that I am not under the influence of alcohol, drugs or anything else that may impair my ability to participate in the Activity. </li>
      	<li><strong>PHOTOGRAPHY &amp; IMAGE USE:</strong> I acknowledge that I may be filmed, photographed or recorded for use by Norfolk Design Inc, and Red Bull. I grant permission for Norfolk Design Inc and Red Bull to use my name, picture, voice and likeness in any manner and media, throughout the world and in perpetuity. I waive any right to inspect or approve finished materials I am in or receive compensation for my participation or any use of my name, picture, voice or likeness. If I do not wish to be filmed, photographed, recorded or appear under these conditions I will leave this area immediately. </li>
      </ol>

      <p>I AM EIGHTEEN (18) YEARS OF AGE OR OLDER. I HAVE READ THIS RELEASE AND WAIVER CAREFULLY, FULLY UNDERSTAND ITS CONTENTS, AND VOLUNTARILY AGREE TO ITS TERMS.</p>
    </div>
  </div>

	<div class="row">
    <div class="span12">
      <button type="submit" class="btn btn-primary">Save changes</button>
      <a type="button" href="<%= register_path %>" class="btn">Cancel</a>
    </div>
	</div>
<% end %>