config/routes.rb
PhotoBooth::Application.routes.draw do
  root :to => 'User#register'

  mount Resque::Server, :at => "/resque"

  match 'register' => 'User#register', :as => 'register'
  match 'photography' => 'Entry#photography', :as => 'entry_photography'
  match 'editing' => 'Entry#editing', :as => 'entry_editing'
  match 'completed' => 'Entry#completed', :as => 'completed_entries'
  match 'last' => 'Entry#last', :as => 'last_entry'
  get 'generate-nickname(/:fullname)' => 'User#generate_nickname', :as => :nickname
  
  resources :image do
    member do
      get 'open' => 'Entry#open_image'
    end
  end

  #resources :download, :only => [:image]

  resources :entry do
    member do
      get 'photography_start'
      get 'photography_stop'
      get 'photography_completed'
        
      get 'editing_start'
      get 'editing_stop'
      get 'editing_completed'
      
      get 'flag'
      get 'delete'
    end
  end

  match 'image/download/:id'  => 'Entry#download_image',  :as => 'download_image'
  match 'image/upload(/:id)'    => 'Entry#upload_image',    :as => 'upload_image'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  require "fileutils" #required for complete_photography - Used to move files to the correct directory

  belongs_to :user
  belongs_to :event
  has_many :images
  belongs_to :selected_image, :class_name => "Image"
  belongs_to :photographer, :class_name => "AdminUser"
  belongs_to :editor, :class_name => "AdminUser"
  
  scope :photography_queue, where("status = ? OR status = ? or status = ?", ENTRY_STATUS_REGISTERED, ENTRY_STATUS_PHOTOGRAPHY_ACTIVE,ENTRY_STATUS_PHOTOGRAPHY_INACTIVE).order("created_at ASC")
  scope :editing_queue, where("status = ? OR status = ? OR status = ?", ENTRY_STATUS_PHOTOGRAPHY_COMPLETE, ENTRY_STATUS_EDITING_ACTIVE, ENTRY_STATUS_EDITING_INACTIVE).order("created_at ASC")
  scope :flagged, where('status = ?', ENTRY_STATUS_FLAGGED_FOR_MODERATION).order("updated_at ASC")
  scope :deleted, where('status = ?', ENTRY_STATUS_DELETED).order("updated_at ASC")
  scope :completed, where('status = ?', ENTRY_STATUS_COMPLETED).order("updated_at ASC")

  # attr_accessor :entry_directory
  # after_save :create_entry_path
  
  
  def start_photography
    self.status = ENTRY_STATUS_PHOTOGRAPHY_ACTIVE
    save = self.save
    if save
      PrivatePub.publish_to("/queue/photo", {:entry_id => self.id,:action => 'start'})
    end   
    return save
  end
  
  def stop_photography
    self.status = ENTRY_STATUS_PHOTOGRAPHY_INACTIVE
    save = self.save
    if save
      PrivatePub.publish_to("/queue/photo", {:entry_id => self.id,:action => 'stop'})
    end
    return save
  end
  
  def complete_photography
    source_path =  File.expand_path PATH_IMAGES_RAW
    files = Dir.glob("#{source_path}/*.{jpg,jpeg,png,gif,JPG,JPEG,PNG,GIF}")
    if files.count == 0
      return false
    else
      self.status = ENTRY_STATUS_PHOTOGRAPHY_COMPLETE
      save = self.save
      if save
        PrivatePub.publish_to("/queue/photo", {:entry_id => self.id,:action => 'complete'})
        Dir.foreach(source_path) do |item|
          next if item == '.' or item == '..' or item.starts_with?('.')
          filename = File.basename(item).to_s
          self.images.create(:tmp_path => source_path+ "/" +filename)
        end
        PrivatePub.publish_to("/queue/edit", {:entry_id => self.id,:action => 'create', :user => self.user, :entry => self, :images => self.images})
      end
      return save
    end
  end

  def start_editing
    self.status = ENTRY_STATUS_EDITING_ACTIVE
    save = self.save
    if save
      PrivatePub.publish_to("/queue/edit", {:entry_id => self.id,:action => 'start'})      
    end   
    return save
  end
  
  def stop_editing
    self.status = ENTRY_STATUS_EDITING_INACTIVE
    save = self.save
    if save
      PrivatePub.publish_to("/queue/edit", {:entry_id => self.id,:action => 'stop'})      
    end
    return save
  end
  
  def complete_editing
    if self.selected_image_id
      self.status = ENTRY_STATUS_COMPLETED    
      save = self.save
      if save
        PrivatePub.publish_to("/queue/edit", {:entry_id => self.id,:action => 'complete'})
        data = self.attributes
        data[:selected_image] = self.selected_image.attributes
        data[:user] = self.user.attributes
        PrivatePub.publish_to("/entry/complete", data)
      end
      return save
    else
      false
    end
  end

  def flag
    self.status = ENTRY_STATUS_FLAGGED_FOR_MODERATION
    self.save
  end

  def delete
    PrivatePub.publish_to("/entry/delete", {:entry_id => self.id,:action => 'delete'})
    self.status = ENTRY_STATUS_DELETED
    self.save
  end  
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  require 'pp'
  
  def photography
    # current_admin_user    
    @entries = Entry.photography_queue
    @has_active = @entries.index{|entry| entry.status == ENTRY_STATUS_PHOTOGRAPHY_ACTIVE}
    @admin_user = current_admin_user    
    
    entry = @entries.first || Entry.new(status: ENTRY_STATUS_PHOTOGRAPHY_ACTIVE)
    
    if can? :manage, entry
      render :action => "photography_queue"
    else
      redirect_to root_path, :notice => "You have to be a photographer to view the queue."
    end

  end

  def editing
    @entries = Entry.editing_queue
    @has_active = @entries.index{|entry| entry.status == ENTRY_STATUS_EDITING_ACTIVE}
    @admin_user = current_admin_user  
    
    entry = @entries.first || Entry.new(status: ENTRY_STATUS_PHOTOGRAPHY_COMPLETE)
    
    if can? :manage, entry
      respond_to do |format|
        format.html {render :action => "editing_queue"}
        format.xml { render :xml => @entries}
        format.json { render :json => @entries.to_json(:include => [:user,:images])}
      end        
    else
      redirect_to root_path, :notice => "You must be an editor to view the queue."
    end
  end

  def open_image
    if params[:id]
      image = Image.find(params[:id])
      image.open
      respond_to do |format|
        format.xml { render :xml => image}
        format.json { render :json => image}
      end            
    end
  end

  def completed
    @completed_entries = Entry.completed
    render :layout => 'gallery'
  end

  def last
    if Entry.editing_queue.count > 0
      @last_entry = Entry.editing_queue.last.images.last
      pp @last_entry
    else
      @last_entry = Entry.completed.last.images.last
    end
    render :layout => 'gallery'
  end

  # /* ***********************************************
  # UTILITY METHODS FOR ALLOWING STATUS SWAPPING AND RESPONDING TO THE CHANGE OF STATUS.
  # THIS NEEDS REFACTORING -- A LOT OF DUPLICATE CODE.
  # *********************************************** */
  def photography_start    
    if params[:id]
      source_path =  File.expand_path PATH_IMAGES_RAW      
      Dir.foreach(source_path) do |item|
        next if item == '.' or item == '..'
        File.delete(source_path +"/"+ item)
      end
      
      
      entry = Entry.find(params[:id])
      if can? :manage, entry
        entry.photographer = current_admin_user
        if entry.start_photography    
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
        end      
      else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
      end
    end
  end
  
  def photography_stop    
    if params[:id]
      entry = Entry.find(params[:id])
      if can? :manage, entry
        entry.photographer = nil
        if entry.stop_photography    
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
        end      
      else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
      end
    end
  end
  
  def photography_completed
    if params[:id]
      entry = Entry.find(params[:id])
      if can? :manage, entry
        entry.photographer = current_admin_user
        if entry.complete_photography    
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => false}
            format.json { render :json => false}
          end
        end      
      else
          respond_to do |format|
            format.xml { render :xml => false}
            format.json { render :json => false}
          end
      end
    end
  end
    
  def editing_start
    if params[:id]
      entry = Entry.find(params[:id])
      
      data = {
        :entry => entry,
        :images => entry.images,
        :user => entry.user
      }
      if can? :manage, entry
        entry.editor = current_admin_user
        if entry.start_editing
          respond_to do |format|
            format.xml { render :xml => data}
            format.json { render :json => data}
          end
        else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
        end
      else
        respond_to do |format|
          format.xml { render :xml => nil}
          format.json { render :json => nil}
        end
      end      
    end
  end
  
  def editing_stop
    if params[:id]
      entry = Entry.find(params[:id])
      if can? :manage, entry
        entry.editor = nil
        if entry.stop_editing
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
        end
      else
        respond_to do |format|
          format.xml { render :xml => nil}
          format.json { render :json => nil}
        end
      end      
    end
  end
  
  def editing_completed
    if params[:id]
      entry = Entry.find(params[:id])
      if can? :manage, entry
        if entry.complete_editing
          Resque.enqueue(EntryUploader,entry.id)
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => false}
            format.json { render :json => false}
          end
        end
      else
        respond_to do |format|
          format.xml { render :xml => false}
          format.json { render :json => false}
        end
      end      
    end
  end

  def flag
    if params[:id]
      entry = Entry.find(params[:id])
      if can? :manage, entry      
        if entry.flag
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
        end      
      else
        respond_to do |format|
          format.xml { render :xml => nil}
          format.json { render :json => nil}
        end
      end
    end    
  end  

  def delete    
    if params[:id]
      entry = Entry.find(params[:id])
      if can? :manage, entry      
        if entry.delete
          respond_to do |format|
            format.xml { render :xml => entry}
            format.json { render :json => entry}
          end
        else
          respond_to do |format|
            format.xml { render :xml => nil}
            format.json { render :json => nil}
          end
        end      
      else
        respond_to do |format|
          format.xml { render :xml => nil}
          format.json { render :json => nil}
        end
      end
    end    
  end  

  def download_image    
    image = Image.find(params[:id])
    path = File.expand_path("./public" + image.file.url(:original,false))
    respond_to do |format|
      format.download {send_file(path)}
    end
  end  

  def upload_image
    if params[:id]
      image = Image.find(params[:id])
    else
      image = Image.create(entry_id: params[:image][:entry_id])
    end
    
    if image
      pp "IMAGE FILE"
      pp params[:image][:file]
      image.file = params[:image][:file]
      if image.save
        entry = Entry.find(image.entry_id)
        entry.update_attributes(selected_image_id: image.id)
        # entry.complete_editing
        redirect_to entry_editing_path, :notice => 'Saved'
      end
    end
  end  
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/views/entry/completed.html.erb
<script type="text/javascript" charset="utf-8">
  var images = JSON.parse("<%= escape_javascript(raw(@completed_entries.to_json(include: [:selected_image, :user]))) %>");
</script>

app/views/entry/editing_queue.html.erb
<%= subscribe_to "/queue/edit" %>

<% if @has_active %>
  <% content_for :body_class do %>editing<% end %>
<% end %>

<h1>Editing Queue</h1>
<div id="editing_queue">
<% if !@entries.blank? %>
  <% @entries.each_with_index do |entry,index| %>
   <% if index % 4 == 0 %>
  <ul class="row-fluid">
   <% end %>
   
    <li id="entry_<%= entry.id %>" class="span3 well<% if entry.editor_id == @admin_user.id %> active owner <% elsif entry.status == ENTRY_STATUS_EDITING_ACTIVE %> active <% end %>"  data-entry-id="<%= entry.id %>">
    <div>
      <p><%= entry.id %></p>
      <div class="data">
        <p><%= "#{entry.user.name_first} #{entry.user.name_last}" %></p>
        <p><%= entry.user.name_nick %></p>
      </div>
      <div class="selected_image">
        <% if entry.selected_image %>
          <div class="">
            <%= image_tag(entry.selected_image.file.url)%>
          </div>
        <% end %>
      
        <%= form_for(Image.new, :url => upload_image_path(Image.new), :html => {:multipart => true, :class => 'edit_image'}) do |f| -%>
          <%= f.hidden_field :entry_id, value: entry.id %>
          <%= f.label :file, "Update Image:" %>
          <%= f.file_field :file, :class => 'image_file' %> <br />
        <% end -%>            
      </div>

      <p class="controls well">
        <%= link_to  editing_start_entry_path(entry, :format => :json), :remote => true, :class => 'remote_action', :data => { :action => 'start-editing'} do %>
          <i class="icon-pencil"></i>Start Editing
        <% end %>
        
        <%= link_to editing_stop_entry_path(entry, :format => :json), :remote => true, :class => 'remote_action', :data => { :action => 'stop-editing'} do %>
          <i class="icon-stop"></i>Stop Editing
        <% end %>
        <%= link_to editing_completed_entry_path(entry, :format => :json), :remote => true, :class => 'remote_action', :data => { :action => 'complete-editing'} do %>          
          <i class="icon-ok"></i>Done Editing
        <% end %>
      </p>
      <p>
        <%= link_to delete_entry_path(entry,:format => :json), :remote => true, :confirm => "are you sure?", :class => 'remote_action delete-entry', :data => { :action => 'delete-entry'} do %>          
          <i class="icon-trash"></i>Delete
        <% end %>
      </p>
<textarea class="userdata"><%= entry.user.name_first %> <%= entry.user.name_last %> aka
<%= entry.user.name_nick %>
</textarea>
            
      <div class="thumbnails well">
        <% if !entry.images.blank? %>
          <% for image in entry.images %>
            <div class="thumbnail">
              <%= link_to(image_tag(image.file.url), download_image_path(image))%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </li>
  <% if index % 4 == 3 %>
    </ul>
  <% end %>
  <% end %>
<% else %>
    <ul class="row-fluid"></ul>
<% end %>
</div>

<% #THIS IS A HIDDEN HTML TEMPLATE TO BE USED BY THE MUSTACHE.JS RENDER - any changes you make to the list item above should be made to this JS template too. %> 
<script class="entry_template" type="text/html">
    <li id="entry_{{entry_id}}" class="span3 well" data-entry-id="{{entry_id}}">
    <div>
      <p>{{entry_id}}</p>
      <div class="data">
        <p>{{user.name_first}} {{user.name_last}}</p>
        <p>{{user.name_nick}}</p>
      </div>
      <div class="selected_image">
          <form accept-charset="UTF-8" action="<%= upload_image_path %>" class="edit_image" enctype="multipart/form-data" method="post">
            <div>
              <input name="utf8" type="hidden" value="✓">
              <input name="authenticity_token" type="hidden" value="{{auth_token}}">
            </div>  						
            <input id="image_entry_id" name="image[entry_id]" type="hidden" value="{{entry_id}}">
            <label for="image_file">Update Image:</label>
            <input class="image_file" name="image[file]" type="file">
          </form>
      </div>

      <p class="controls well">
        <%= link_to "entry/{{entry_id}}/editing_start.json", :remote => true, :class => 'remote_action', :data => { :action => 'start-editing'} do %>
          <i class="icon-pencil"></i>Start Editing
        <% end %>
        <%= link_to "entry/{{entry_id}}/editing_stop.json", :remote => true, :class => 'remote_action', :data => { :action => 'stop-editing'} do %>        
          <i class="icon-stop"></i>Stop Editing
        <% end %>
        <%= link_to "entry/{{entry_id}}/editing_completed.json", :remote => true, :class => 'remote_action', :data => { :action => 'complete-editing'} do %>        
          <i class="icon-ok"></i>Done Editing
        <% end %>
      </p>
      <p>
        <%= link_to "entry/{{entry_id}}/delete", :remote => true, :confirm => "are you sure?", :class => 'remote_action delete-entry', :data => { :action => 'delete-entry'} do %>        
          <i class="icon-trash"></i>Delete
        <% end %>
      </p>
    </div>
    <textarea class="userdata">{{user.name_first}} {{user.name_last}} aka
{{user.name_nick}}
</textarea>
    <div class="thumbnails well"></div>
  </li>  
</script>
<% # END THIS IS A HIDDEN HTML TEMPLATE TO BE USED BY THE MUSTACHE.JS RENDER %> 


<% #THIS IS A HIDDEN HTML TEMPLATE TO BE USED BY THE MUSTACHE.JS RENDER - any changes you make to the list item above should be made to this JS template too. %> 
<script class="entry_form_template" type="text/html">  
  <div class="thumbnail">
      <a href="/image/download/{{id}}.download"><img src="{{local_file}}"></a>
  </div>  
</script>
<% # END THIS IS A HIDDEN HTML TEMPLATE TO BE USED BY THE MUSTACHE.JS RENDER %> 

app/views/entry/last.html.erb
<% if @last_entry %>
  <%= image_tag(@last_entry.file.url(:original), class: "last-entry-image") %>
<% end %>

app/views/entry/photography_queue.html.erb
<%= subscribe_to "/queue/photo" %>

<% if @has_active %>
	<% content_for :body_class do %>editing<% end %>
<% end %>



<h1>Photography Queue</h1>
<div id="photography_queue">
<% if !@entries.blank? %>
  <% @entries.each_with_index do |entry,index| %>
  	<% if index % 4 == 0 %>
		<ul class="row-fluid">
	<% end %>
    <li id="entry_<%= entry.id %>"class="span3 well <% if entry.photographer_id == @admin_user.id %>active owner<% end %>"  data-entry-id="<%= entry.id %>">
		<div>
			<p><%= entry.id %></p>
			<p><%= "#{entry.user.name_first} #{entry.user.name_last}" %></p>
			<p><%= entry.user.name_nick %></p>
			<p class="controls well">
				<%= link_to photography_start_entry_path(entry,:format => :json), :remote => true, :class => 'remote_action', :data => { :action => 'start-photography'} do %>
					<i class="icon-play"></i>Start Photography
				<% end %>
				<%= link_to photography_stop_entry_path(entry, :format => :json), :remote => true, :confirm => "Are you sure? This will delete any pictures taken so far.", :class => 'remote_action', :data => { :action => 'stop-photography'} do %>					
					<i class="icon-stop"></i>Stop Photography
				<% end %>
				<%= link_to photography_completed_entry_path(entry, :format => :json), :remote => true, :class => 'remote_action', :data => { :action => 'complete-photography'} do %>					
					<i class="icon-eject"></i>Complete Photography
				<% end %>
			</p>
			<p>
				<%= link_to delete_entry_path(entry,:format => :json), :remote => true, :confirm => "are you sure?", :class => 'remote_action', :data => { :action => 'delete-entry'} do %>					
					<i class="icon-trash"></i>Delete
				<% end %>
			</p>
		</div>
	</li>
	<% if index % 4 == 3 %>
		</ul>
	<% end %>
  <% end %>
<% else %>
  <ul class="row-fluid"></ul>
<% end %>
	
	
</div>

<% #THIS IS A HIDDEN HTML TEMPLATE TO BE USED BY THE MUSTACHE.JS RENDER - any changes you make to the list item above should be made to this JS template too. %> 
<script class="entry_template" type="text/html">
	<li id="entry_{{entry_id}}" class="span3 well" data-entry-id="{{entry_id}}">
		<div>
			<p>{{entry_id}}</p>
			<p>{{user.name_first}} {{user.name_last}}</p>
			<p>{{user.name_nick}}</p>
			<p class="controls well">
				<%= link_to "entry/{{entry_id}}/photography_start.json", :remote => true, :class => 'remote_action', :data => { :action => 'start-photography'} do %>
					<i class="icon-play"></i>Start Photography
				<% end %>
				<%= link_to "entry/{{entry_id}}/photography_stop.json", :remote => true, :confirm => "are you sure?", :class => 'remote_action', :data => { :action => 'stop-photography'} do %>
					<i class="icon-stop"></i>Stop Photography
				<% end %>
				<%= link_to "entry/{{entry_id}}/photography_completed.json", :remote => true, :class => 'remote_action', :data => { :action => 'complete-photography'} do %>
					<i class="icon-eject"></i>Complete Photography
				<% end %>
			</p>
			<p><%= link_to "Delete", "entry/{{entry_id}}/delete.json", :remote => true, :confirm => "are you sure?", :class => 'remote_action', :data => { :action => 'delete-entry'} %></p>
		</div>
	</li>
</script>
<% #END THIS IS A HIDDEN HTML TEMPLATE TO BE USED BY THE MUSTACHE.JS RENDER %> 