config/routes.rb
PhotoBooth::Application.routes.draw do
  root :to => 'User#register'

  mount Resque::Server, :at => "/resque"

  match 'register' => 'User#register', :as => 'register'
  match 'photography' => 'Entry#photography', :as => 'entry_photography'
  match 'editing' => 'Entry#editing', :as => 'entry_editing'
  match 'completed' => 'Entry#completed', :as => 'completed_entries'
  match 'last' => 'Entry#last', :as => 'last_entry'
  get 'generate-nickname(/:fullname)' => 'User#generate_nickname', :as => :nickname
  
  resources :image do
    member do
      get 'open' => 'Entry#open_image'
    end
  end

  #resources :download, :only => [:image]

  resources :entry do
    member do
      get 'photography_start'
      get 'photography_stop'
      get 'photography_completed'
        
      get 'editing_start'
      get 'editing_stop'
      get 'editing_completed'
      
      get 'flag'
      get 'delete'
    end
  end

  match 'image/download/:id'  => 'Entry#download_image',  :as => 'download_image'
  match 'image/upload(/:id)'    => 'Entry#upload_image',    :as => 'upload_image'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PhotoBooth</title>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "mustache", "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body<% if content_for?(:body_class) %> class="<%= yield(:body_class) %>"<% end %>>
  <%= subscribe_to "/entry/delete" %>

<div class="container-fluid">
    <%= link_to "logout", destroy_admin_user_session_path, html_options = {:class => 'btn btn-primary btn-mini'} %>
    <% if flash[:notice] %>
    <div id="notice">
        <%= flash[:notice] %>
    </div>
    <% end %>
    
	
<%= yield %>

</div>
</body>
</html>

app/views/layouts/gallery.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PhotoBooth</title>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag 'gallery'%>
  
  <%= csrf_meta_tags %>
</head>
<body<% if content_for?(:body_class) %> class="<%= yield(:body_class) %>"<% end %>>

<div id="container" class="completed">
<%= yield %>
</div>
<%= javascript_include_tag "mustache", "application", "gallery", "last_entry" %>
<%= subscribe_to "/entry/complete" %>
<%= subscribe_to "/queue/edit" %>

</body>
</html>